// automatically generated by the FlatBuffers compiler, do not modify

package Neodroid.FBS;

import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.Struct;

import java.nio.ByteBuffer;

@SuppressWarnings("unused")
public final class FQuaternion extends Struct {
  public static int createFQuaternion(FlatBufferBuilder builder, double x, double y, double z, double w) {
    builder.prep(8, 32);
    builder.putDouble(w);
    builder.putDouble(z);
    builder.putDouble(y);
    builder.putDouble(x);
    return builder.offset();
  }

  public FQuaternion __assign(int _i, ByteBuffer _bb) {
    __init(_i, _bb);
    return this;
  }

  public void __init(int _i, ByteBuffer _bb) {
    bb_pos = _i;
    bb = _bb;
  }

  public double x() {
    return bb.getDouble(bb_pos + 0);
  }

  public double y() {
    return bb.getDouble(bb_pos + 8);
  }

  public double z() {
    return bb.getDouble(bb_pos + 16);
  }

  public double w() {
    return bb.getDouble(bb_pos + 24);
  }
}

