// automatically generated by the FlatBuffers compiler, do not modify

package Neodroid.FBS;

import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.Struct;

import java.nio.ByteBuffer;

@SuppressWarnings("unused")
public final class FRange extends Struct {
  public static int createFRange(FlatBufferBuilder builder, int decimalGranularity, float maxValue, float minValue) {
    builder.prep(4, 12);
    builder.putFloat(minValue);
    builder.putFloat(maxValue);
    builder.putInt(decimalGranularity);
    return builder.offset();
  }

  public FRange __assign(int _i, ByteBuffer _bb) {
    __init(_i, _bb);
    return this;
  }

  public void __init(int _i, ByteBuffer _bb) {
    bb_pos = _i;
    bb = _bb;
  }

  public int decimalGranularity() {
    return bb.getInt(bb_pos + 0);
  }

  public float maxValue() {
    return bb.getFloat(bb_pos + 4);
  }

  public float minValue() {
    return bb.getFloat(bb_pos + 8);
  }
}

