// automatically generated by the FlatBuffers compiler, do not modify

package Neodroid.FBS;

import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.Struct;

import java.nio.ByteBuffer;

@SuppressWarnings("unused")
public final class FVector2 extends Struct {
  public static int createFVector2(FlatBufferBuilder builder, double x, double y) {
    builder.prep(8, 16);
    builder.putDouble(y);
    builder.putDouble(x);
    return builder.offset();
  }

  public FVector2 __assign(int _i, ByteBuffer _bb) {
    __init(_i, _bb);
    return this;
  }

  public void __init(int _i, ByteBuffer _bb) {
    bb_pos = _i;
    bb = _bb;
  }

  public double x() {
    return bb.getDouble(bb_pos + 0);
  }

  public double y() {
    return bb.getDouble(bb_pos + 8);
  }
}

